### ISSUE TITLE
Inquiry about training code

### ISSUE THREAD

**Issue by ItsThanhTung** [bytetriper/LM4LV#2]
During training, there are two images (LQ and HQ) as input to the models. Correct me if I am wrong. In `embed_tokens ` function [(embed_tokens  function),](https://github.com/bytetriper/LM4LV/blob/main/src/model/LM4LV.py#L463) the `vision_placeholder` will be replaced with `vision_embed`. Is there any chance that the training code accidentally includes the target `vision_embed` in the inputs_embeds?

**Comment by bytetriper** [comment]
Yes, in the training phase both LQ and HQ is include into the training sequence, and it's doing a next-feature prediction based on all previous GT features, which is illustrated in the paper.

Let's compare it to LLM training. In training, LLM sees all GT tokens from 1-n and is required to predict the n+1 token. This allows LLM to model a next token probability distribution $\mathbb{P}(x_{n+1}\mid x_{1,\ldots, n})$, which can be used for auto-regressive generation afterwards. Here we're doing a next-feature prediction based on all GT visual features (and tokens). As next feature is fixed and not a distr, this pushed LLM to model $\mathbb{E}[x_{n+1}\mid x_{1,\ldots, n}]$.

In the inference stage the LLM gets only LQ features and it generate HQ features auto-regressively with learned expectation. This is some emu-style regression I think, refer to [emu](https://arxiv.org/abs/2312.13286) if I'm not making this clear 🚀

**Comment by ItsThanhTung** [comment]
So it is possible that during training the LLM might attend to HQ image tokens.

**Comment by ItsThanhTung** [comment]
So it is possible that during training the LLM might attend to HQ image tokens.

**Comment by bytetriper** [comment]
yes, during training the LLM sees previous HQ tokens when trying to predict the next HQ token.

**Comment by ItsThanhTung** [comment]
Thank you for your clear explanation.
